### ISSUE TITLE
running locally fireboy and watergirl

### ISSUE THREAD

**Issue by Eyal-Engel** [pavel-skala/Fireboy-and-Watergirl#2]
hi how r u?

I ran the index.html file but i see only black window?

I would like if u can explain me how to run this on my pc.

TNX :)

**Comment by pavel-skala** [comment]
Hi,
you can run it with Live Server extension in Visual Studio Code. 
https://www.youtube.com/watch?v=_wue59ldqMg

This is the reason why it doesn't work
![image](https://github.com/pavel-skala/Fireboy-and-Watergirl/assets/105449065/420e6e38-dbd3-4c4c-a462-d2c12e4cf9ea)
